{{- $fullName := include "popularity-service.fullname" . -}}
{{- $labels := include "popularity-service.labels" . -}}
{{- $selectorLabels := include "popularity-service.selectorLabels" . -}}
{{- $deploymentLabel := include "popularity-service.deployment" . -}}
{{- $serviceAccountName := include "popularity-service.serviceAccountName" . -}}
{{- $chartName := .Chart.Name -}}
{{- $chartAppVersion := .Chart.AppVersion -}}
{{- $values := .Values -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    popularity-service: {{- $labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      popularity-service:
      {{- $selectorLabels | nindent 6 }}
      {{- $deploymentLabel | indent 6 }}
  {{- with $values.deployStrategy }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
  template:
    metadata:
      {{- with $values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        popularity-service:
          {{- $selectorLabels | nindent 8 }}
          {{- $deploymentLabel | indent 8 }}
    spec:
      {{ if $values.dockerConfigJson }}
      imagePullSecrets:
        - name: regcred-{{ $fullName }}
      {{ else }}
      {{- with $values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ $serviceAccountName }}
      securityContext:
        {{- toYaml $values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $chartName }}
          securityContext:
            {{- toYaml $values.securityContext | nindent 12 }}
          image: "{{ $values.image.repository }}:{{ $values.image.tag | default $chartAppVersion }}"
          imagePullPolicy: {{ $values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $values.service.port }}
              protocol: TCP
          {{- if $values.app.secret -}}
          envFrom:
            - secretRef:
                name: {{ $fullName }}-secret-configuration
          {{- end }}
          env:
            - name: POPULARITY-SERVICE_APP_VERSION
              value: {{ $values.image.tag }}
            - name: SPRING_PROFILES_ACTIVE
              value: {{ $values.environment }}
            - name: JAVA_TOOL_OPTIONS
              value: {{ $values.jvmOptions }}
                     {{- with $values.customEnv }}
                       {{- toYaml . | nindent 12 }}
                     {{- end }}
          volumeMounts:
            - mountPath: /config
              name: config
              readOnly: true
                   {{- if $values.app.secretFiles }}
            - mountPath: /config/secrets
              name: secrets
              readOnly: true
                   {{- end }}
          resources:
             {{- toYaml $values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            defaultMode: 420
            name: {{ $fullName }}-config
        {{- if $values.app.secretFiles }}
        - name: secrets
          secret:
            defaultMode: 420
            secretName: {{ $fullName }}-secret-files-configuration
        {{- end }}