popularity-service:
  environment: live, gb1
  config:
    files:
      application-gb1.yaml: |-

popularity-service-job:
  image:
    repository: popularity-service
    pullPolicy: Never
    tag: 0.1.0
  args: []