#resources:
#  limits:
#    memory: "1Gi"
#    cpu: "1"
#  requests:
#    memory: "512Mi"
#    cpu: "500m"
#image:
##  //TODO
#  repository: your-docker-image
#  tag: latest
#  pullPolicy: IfNotPresent
#schedule: "*/5 * * * *" # Optional: Use if deploying a CronJob
#containerCommand:
#  - "java"
#  - "-jar"
##  - //TODO
#  - "your-scheduler-jar.jar"
