{{- $fullName := include "popularity-service.fullname" . -}}
{{- $labels := include "popularity-service.labels" . -}}
{{- $values := .Values -}}
{{- range $clusterName, $clusterValue := .Values.clusters }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-{{ $clusterName }}-config
  labels:
    hounds.cluster: {{ $clusterName }}
    {{- $labels | nindent 4 }}
data:
  {{ if $values.config }}
  {{- end }}
  {{ toYaml $values.config | nindent 2 }}
  {{ if .app.configFiles }}
  {{ toYaml .app.configFiles | nindent 2 }}
  {{- end }}
---
{{- end }}