{{- if .Values.app.secret -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "popularity-service.fullname" $ }}-secret-configuration
stringData:
  {{ toYaml .Values.app.secret | nindent 2 }}
{{- end }}
---
{{- if .Values.app.secretFiles -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "popularity-service.fullname" $ }}-secret-files-configuration
data:
{{ toYaml .Values.app.secretFiles | nindent 2 }}
{{- end }}
