{{/*apiVersion: batch/v1*/}}
{{/*kind: Job*/}}
{{/*metadata:*/}}
{{/*  name: {{ .Release.Name }}-job*/}}
{{/*  labels:*/}}
{{/*    app: {{ .Release.Name }}-job*/}}
{{/*spec:*/}}
{{/*  template:*/}}
{{/*    metadata:*/}}
{{/*      labels:*/}}
{{/*        app: {{ .Release.Name }}-job*/}}
{{/*    spec:*/}}
{{/*      restartPolicy: Never*/}}
{{/*      containers:*/}}
{{/*        - name: job-runner*/}}
{{/*          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"*/}}
{{/*          args: {{ .Values.args | toJson }}*/}}

apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "popularity-service.fullname" . }}
  labels:
    {{- include "popularity-service.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "popularity-service.selectorLabels" . | nindent 12 }}
        spec:
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.global.image.pullPolicy }}
              env:
                {{- range .Values.global.env }}
                - name: {{ .name }}
                  value: {{ .value | quote }}
                {{- end }}
              resources:
                {{- toYaml .Values.global.resources | nindent 16 }}
          restartPolicy: {{ .Values.global.restartPolicy | default "Never" }}